# Generated by Django 2.2.5 on 2019-09-15 08:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='user',
        ),
        migrations.AlterField(
            model_name='tournament',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 15, 12, 55, 34, 216762)),
        ),
    ]
