# Generated by Django 2.2.3 on 2019-09-15 18:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0002_auto_20190915_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='host',
        ),
        migrations.AlterField(
            model_name='tournament',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 15, 22, 44, 17, 327094)),
        ),
    ]
