# Generated by Django 2.2.3 on 2019-09-15 18:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0003_auto_20190915_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 15, 22, 44, 46, 620601)),
        ),
    ]
